class PagesController < ApplicationController
  def home
  end

  def search
    query = params['query']
    # send query to stackoverflow...
    render json: %q(
    { "items":[
      {
         "user":{
            "reputation":363279,
            "user_id":19068,
            "user_type":"registered",
            "profile_image":"https://www.gravatar.com/avatar/1d2d3229ed1961d2bd81853242493247?s=128&d=identicon&r=PG",
            "display_name":"Quentin",
            "link":"http://stackoverflow.com/users/19068/quentin"
         },
         "post_count":122,
         "score":235
      },
      {
         "user":{
            "reputation":147169,
            "user_id":965051,
            "user_type":"registered",
            "profile_image":"http://i.stack.imgur.com/XgLe7.gif?s=128&g=1",
            "display_name":"adeneo",
            "link":"http://stackoverflow.com/users/965051/adeneo"
         },
         "post_count":95,
         "score":193
      },
      {
         "user":{
            "reputation":329390,
            "user_id":157247,
            "user_type":"registered",
            "accept_rate":90,
            "profile_image":"https://www.gravatar.com/avatar/ca3e484c121268e4c8302616b2395eb9?s=128&d=identicon&r=PG",
            "display_name":"T.J. Crowder",
            "link":"http://stackoverflow.com/users/157247/t-j-crowder"
         },
         "post_count":111,
         "score":190
      },
      {
         "user":{
            "reputation":79750,
            "user_id":519413,
            "user_type":"registered",
            "accept_rate":96,
            "profile_image":"https://www.gravatar.com/avatar/7839089cd91dc5cc5eb1e0cdbf3312ed?s=128&d=identicon&r=PG",
            "display_name":"Rory McCrossan",
            "link":"http://stackoverflow.com/users/519413/rory-mccrossan"
         },
         "post_count":92,
         "score":184
      },
      {
         "user":{
            "reputation":31625,
            "user_id":3001736,
            "user_type":"registered",
            "accept_rate":76,
            "profile_image":"https://www.gravatar.com/avatar/196b4f82256d7e597dcb0027167733d8?s=128&d=identicon&r=PG",
            "display_name":"Amit Joki",
            "link":"http://stackoverflow.com/users/3001736/amit-joki"
         },
         "post_count":106,
         "score":166
      },
      {
         "user":{
            "reputation":62537,
            "user_id":1009603,
            "user_type":"registered",
            "accept_rate":50,
            "profile_image":"http://i.stack.imgur.com/spzYW.jpg?s=128&g=1",
            "display_name":"PSL",
            "link":"http://stackoverflow.com/users/1009603/psl"
         },
         "post_count":98,
         "score":156
      },
      {
         "user":{
            "reputation":8361,
            "user_id":367138,
            "user_type":"registered",
            "profile_image":"https://www.gravatar.com/avatar/459fe9524294ad4b1a9b0f192a0fecaf?s=128&d=identicon&r=PG&f=1",
            "display_name":"Alexander",
            "link":"http://stackoverflow.com/users/367138/alexander"
         },
         "post_count":86,
         "score":144
      },
      {
         "user":{
            "reputation":173079,
            "user_id":816620,
            "user_type":"registered",
            "accept_rate":63,
            "profile_image":"https://www.gravatar.com/avatar/162aa26d42813f31a21ced4bc9195f23?s=128&d=identicon&r=PG",
            "display_name":"jfriend00",
            "link":"http://stackoverflow.com/users/816620/jfriend00"
         },
         "post_count":109,
         "score":136
      },
      {
         "user":{
            "reputation":33995,
            "user_id":1945651,
            "user_type":"registered",
            "accept_rate":80,
            "profile_image":"https://www.gravatar.com/avatar/4b97ded43d95fa7eb43ac635971ad213?s=128&d=identicon&r=PG",
            "display_name":"JLRishe",
            "link":"http://stackoverflow.com/users/1945651/jlrishe"
         },
         "post_count":94,
         "score":135
      },
      {
         "user":{
            "reputation":192071,
            "user_id":182668,
            "user_type":"registered",
            "accept_rate":71,
            "profile_image":"https://www.gravatar.com/avatar/b19917aa04a6839aef577f1117c71d48?s=128&d=identicon&r=PG",
            "display_name":"Pointy",
            "link":"http://stackoverflow.com/users/182668/pointy"
         },
         "post_count":47,
         "score":128
      },
      {
         "user":{
            "reputation":82817,
            "user_id":14104,
            "user_type":"registered",
            "profile_image":"https://www.gravatar.com/avatar/760b4da77fd54d37c104029ff1f56749?s=128&d=identicon&r=PG",
            "display_name":"epascarello",
            "link":"http://stackoverflow.com/users/14104/epascarello"
         },
         "post_count":96,
         "score":125
      },
      {
         "user":{
            "reputation":58475,
            "user_id":949476,
            "user_type":"registered",
            "profile_image":"https://www.gravatar.com/avatar/8feb0675d5ebf4c11ed13885347cc970?s=128&d=identicon&r=PG",
            "display_name":"dfsq",
            "link":"http://stackoverflow.com/users/949476/dfsq"
         },
         "post_count":84,
         "score":114
      },
      {
         "user":{
            "reputation":274652,
            "user_id":218196,
            "user_type":"registered",
            "accept_rate":100,
            "profile_image":"http://i.stack.imgur.com/4P5DY.jpg?s=128&g=1",
            "display_name":"Felix Kling",
            "link":"http://stackoverflow.com/users/218196/felix-kling"
         },
         "post_count":58,
         "score":113
      },
      {
         "user":{
            "reputation":14915,
            "user_id":913124,
            "user_type":"registered",
            "accept_rate":100,
            "profile_image":"https://www.gravatar.com/avatar/43bc7faac07fe32360a924768878020b?s=128&d=identicon&r=PG&f=1",
            "display_name":"Christos",
            "link":"http://stackoverflow.com/users/913124/christos"
         },
         "post_count":60,
         "score":104
      },
      {
         "user":{
            "reputation":31443,
            "user_id":1719752,
            "user_type":"registered",
            "accept_rate":88,
            "profile_image":"http://i.stack.imgur.com/oxeDF.jpg?s=128&g=1",
            "display_name":"Milind Anantwar",
            "link":"http://stackoverflow.com/users/1719752/milind-anantwar"
         },
         "post_count":64,
         "score":104
      },
      {
         "user":{
            "reputation":70340,
            "user_id":1903116,
            "user_type":"registered",
            "accept_rate":100,
            "profile_image":"http://i.stack.imgur.com/w6Ffg.jpg?s=128&g=1",
            "display_name":"thefourtheye",
            "link":"http://stackoverflow.com/users/1903116/thefourtheye"
         },
         "post_count":25,
         "score":103
      },
      {
         "user":{
            "reputation":21707,
            "user_id":2138752,
            "user_type":"registered",
            "accept_rate":59,
            "profile_image":"https://www.gravatar.com/avatar/6a962ecd85feb26e0a6882c8cb161ec1?s=128&d=identicon&r=PG&f=1",
            "display_name":"Bhojendra Nepal",
            "link":"http://stackoverflow.com/users/2138752/bhojendra-nepal"
         },
         "post_count":90,
         "score":102
      },
      {
         "user":{
            "reputation":4341,
            "user_id":4364303,
            "user_type":"registered",
            "accept_rate":100,
            "profile_image":"http://i.stack.imgur.com/8FFJB.jpg?s=128&g=1",
            "display_name":"Mouser",
            "link":"http://stackoverflow.com/users/4364303/mouser"
         },
         "post_count":121,
         "score":95
      },
      {
         "user":{
            "reputation":38851,
            "user_id":2680216,
            "user_type":"registered",
            "profile_image":"http://i.stack.imgur.com/K877D.png?s=128&g=1",
            "display_name":"Josh Crozier",
            "link":"http://stackoverflow.com/users/2680216/josh-crozier"
         },
         "post_count":53,
         "score":94
      },
      {
         "user":{
            "reputation":157275,
            "user_id":263525,
            "user_type":"registered",
            "accept_rate":84,
            "profile_image":"https://www.gravatar.com/avatar/ec289925069b35f18f1230b90dc654e5?s=128&d=identicon&r=PG",
            "display_name":"dystroy",
            "link":"http://stackoverflow.com/users/263525/dystroy"
         },
         "post_count":21,
         "score":93
      }
   ],
   "has_more":false,
   "quota_max":300,
   "quota_remaining":296
})
  end
end
